# Generated by Django 3.0.5 on 2020-04-12 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('msa', '0002_auto_20200412_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptedpet',
            name='pet_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msa.PetInfo'),
        ),
        migrations.AlterField(
            model_name='adoptedpet',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
