# Generated by Django 3.0.5 on 2020-04-13 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msa', '0003_auto_20200412_1459'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
